[pytest]
# Wo pytest nach Tests sucht
testpaths = tests

# Namenskonventionen (Standard, hier explizit dokumentiert)
python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts = --cov=processing-service --cov=collector-service --cov=api-service --cov-report=term-missing